// This file is automatically generated by qtc from "basepage.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line basepage.qtpl:1
package templates

//line basepage.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line basepage.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line basepage.qtpl:2
type Page interface {
	//line basepage.qtpl:2
	Title() string
	//line basepage.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
	//line basepage.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
	//line basepage.qtpl:2
	Menu() string
	//line basepage.qtpl:2
	StreamMenu(qw422016 *qt422016.Writer)
	//line basepage.qtpl:2
	WriteMenu(qq422016 qtio422016.Writer)
	//line basepage.qtpl:2
	Body() string
	//line basepage.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
	//line basepage.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
	//line basepage.qtpl:2
	Footer() string
	//line basepage.qtpl:2
	StreamFooter(qw422016 *qt422016.Writer)
	//line basepage.qtpl:2
	WriteFooter(qq422016 qtio422016.Writer)
//line basepage.qtpl:2
}

//line basepage.qtpl:10
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
	//line basepage.qtpl:10
	qw422016.N().S(`
 <html>
    <head>
      <title>`)
	//line basepage.qtpl:13
	p.StreamTitle(qw422016)
	//line basepage.qtpl:13
	qw422016.N().S(`</title>
      <link rel="stylesheet" type="text/css" href="/dist/css/app.css">
    </head>
    <body>
      <div id="top_menu">`)
	//line basepage.qtpl:17
	p.StreamMenu(qw422016)
	//line basepage.qtpl:17
	qw422016.N().S(`</div>
      <div id="main_content">`)
	//line basepage.qtpl:18
	p.StreamBody(qw422016)
	//line basepage.qtpl:18
	qw422016.N().S(`</div>
      <div id="app"></div>
      <div id="footer">`)
	//line basepage.qtpl:20
	p.StreamFooter(qw422016)
	//line basepage.qtpl:20
	qw422016.N().S(`</div>
      <script type="text/javascript" src="/dist/js/bundle.js"></script>
    </body>
 </html>
`)
//line basepage.qtpl:24
}

//line basepage.qtpl:24
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
	//line basepage.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line basepage.qtpl:24
	StreamPageTemplate(qw422016, p)
	//line basepage.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line basepage.qtpl:24
}

//line basepage.qtpl:24
func PageTemplate(p Page) string {
	//line basepage.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
	//line basepage.qtpl:24
	WritePageTemplate(qb422016, p)
	//line basepage.qtpl:24
	qs422016 := string(qb422016.B)
	//line basepage.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
	//line basepage.qtpl:24
	return qs422016
//line basepage.qtpl:24
}

//line basepage.qtpl:27
type BasePage struct{}

//line basepage.qtpl:30
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line basepage.qtpl:30
qw422016.N().S(`This is a base title`) }

//line basepage.qtpl:30
//line basepage.qtpl:30
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
	//line basepage.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line basepage.qtpl:30
	p.StreamTitle(qw422016)
	//line basepage.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line basepage.qtpl:30
}

//line basepage.qtpl:30
func (p *BasePage) Title() string {
	//line basepage.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
	//line basepage.qtpl:30
	p.WriteTitle(qb422016)
	//line basepage.qtpl:30
	qs422016 := string(qb422016.B)
	//line basepage.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
	//line basepage.qtpl:30
	return qs422016
//line basepage.qtpl:30
}

//line basepage.qtpl:31
func (p *BasePage) StreamMenu(qw422016 *qt422016.Writer) {
	//line basepage.qtpl:31
	qw422016.N().S(`<span><a href="/">Home</a></span>`)
//line basepage.qtpl:31
}

//line basepage.qtpl:31
func (p *BasePage) WriteMenu(qq422016 qtio422016.Writer) {
	//line basepage.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line basepage.qtpl:31
	p.StreamMenu(qw422016)
	//line basepage.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line basepage.qtpl:31
}

//line basepage.qtpl:31
func (p *BasePage) Menu() string {
	//line basepage.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
	//line basepage.qtpl:31
	p.WriteMenu(qb422016)
	//line basepage.qtpl:31
	qs422016 := string(qb422016.B)
	//line basepage.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
	//line basepage.qtpl:31
	return qs422016
//line basepage.qtpl:31
}

//line basepage.qtpl:32
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line basepage.qtpl:32
qw422016.N().S(`This is a base body`) }

//line basepage.qtpl:32
//line basepage.qtpl:32
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
	//line basepage.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line basepage.qtpl:32
	p.StreamBody(qw422016)
	//line basepage.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line basepage.qtpl:32
}

//line basepage.qtpl:32
func (p *BasePage) Body() string {
	//line basepage.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
	//line basepage.qtpl:32
	p.WriteBody(qb422016)
	//line basepage.qtpl:32
	qs422016 := string(qb422016.B)
	//line basepage.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
	//line basepage.qtpl:32
	return qs422016
//line basepage.qtpl:32
}

//line basepage.qtpl:33
func (p *BasePage) StreamFooter(qw422016 *qt422016.Writer) {
//line basepage.qtpl:33
qw422016.N().S(`&copy; 2016 - Acme Co.`) }

//line basepage.qtpl:33
//line basepage.qtpl:33
func (p *BasePage) WriteFooter(qq422016 qtio422016.Writer) {
	//line basepage.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line basepage.qtpl:33
	p.StreamFooter(qw422016)
	//line basepage.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line basepage.qtpl:33
}

//line basepage.qtpl:33
func (p *BasePage) Footer() string {
	//line basepage.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
	//line basepage.qtpl:33
	p.WriteFooter(qb422016)
	//line basepage.qtpl:33
	qs422016 := string(qb422016.B)
	//line basepage.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
	//line basepage.qtpl:33
	return qs422016
//line basepage.qtpl:33
}
