package product

// Yep, still visible within this package
var	products_seed = []Product{
	{1, "hot sauce", "hot_sauce"},
	{2, "chips", "chips"},
	{3, "mayonnaise", "mayo"},
	{4, "cake", "cake"},
	{5, "sliced bread", "sliced_bread"},
	{6, "soda", "soda"},
	{7, "wonder bread", "wonder_bread"},
	{8, "wheat bread", "wheat_bread"},
	{9, "barbeque sauce", "barbeque_sauce"},
	{10, "cake bar", "cake_bar"},
	{11, "water", "water"},
	{12, "donuts", "donuts"},
	{13, "muffins", "muffins"},
	{14, "salad dressing", "salad_dressing"},
	{15, "ice cream", "ice_cream"},
	{16, "steak", "steak"},
	{17, "cookies", "cookies"},
	{18, "milk", "milk"},
	{19, "eggs", "eggs"},
	{20, "trail mix", "trail_mix"},
	{21, "mustard", "mustard"},
	{22, "pickle", "pickle"},
	{23, "horseradish", "horseradish"},
	{24, "frozen vegetables", "frozen_vegetables"},
	{25, "dip", "dip"},
	{26, "olive oil", "olive_oil"},
	{27, "soybean oil", "soybean_oil"},
	{28, "canola oil", "canola_oil"},
	{29, "coconut oil", "coconut_oil"},
	{30, "coconut", "coconut"},
	{31, "cocoa", "cocoa"},
	{32, "condensed milk", "condensed_milk"},
	{33, "vinegar", "vinegar"},
	{34, "marmalade jam", "marmalade_jame"},
	{35, "popcorn", "popcorn"},
	{36, "soup", "soup"},
	{37, "sweet corn", "sweet_corn"},
	{38, "hairspray", "hairspray"},
	{39, "snack bar", "snack_bar"},
	{40, "airborne", "airborne"},
	{41, "spinach", "spinach"},
	{42, "ketchup", "ketchup"},
	{43, "rice", "rice"},
	{44, "sugar", "sugar"},
	{45, "wine", "wine"},
	{46, "whiskey", "whiskey"},
	{47, "agave", "agave"},
	{48, "honey", "honey"},
	{49, "lemon", "lemon"},
	{50, "banana", "banana"},
	{51, "sausage", "sausage"},
	{52, "pizza", "pizza"},
	{53, "pasta", "pasta"},
	{54, "crackers", "crackers"},
	{55, "tuna", "tuna"},
	{56, "salmon", "salmon"},
	{57, "cream cheese", "cream_cheese"},
	{58, "cottage cheese", "cottage_cheese"},
	{59, "granola bar", "granola_bar"},
	{60, "beef", "beef"},
	{61, "beef jerky", "beef_jerky"},
	{62, "chicken", "chicken"},
	{63, "turducken", "turducken"},
	{64, "salt", "salt"},
	{65, "black pepper", "black_pepper"},
}
